name: Build Containers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [vulkan-radv, vulkan-amdvlk, rocm, cuda, cpu]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          HTTP_PROXY: ""
          HTTPS_PROXY: ""
          http_proxy: ""
          https_proxy: ""
        with:
          context: .
          file: toolboxes/Dockerfile.${{ matrix.tag }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.tag }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.tag }}:${{ github.sha }}
          build-args: |
            REPO=https://github.com/ggerganov/llama.cpp.git
            BRANCH=master
          provenance: false